export const changeWidthLong='header/changeWidthLong'
export const changeWidthShort='header/changeWidthShort'
export const changeAjax='header/changeAjax'
export const searchInfoOver='header/searchInfoOver'
export const searchInfoLeave='header/searchInfoLeave'
export const OnChangeIndex='header/OnChangeIndex'
